learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Topics page
    path('topics/', views.topics, name='topics'),
    # Single topic page
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page to add a topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page to add an entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page to edit an existing entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# To modify data used by learning log application:
# 1. Modify models.py
# 2. Call python manage.py makemigrations on learning_logs
# 3. Tell django to migrate the project (python manage.py migrate)
# 4. Add it to the admin models


# Create your models here.
class Topic(models.Model):
    """A topic user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model"""
        return self.text


class Entry(models.Model):
    """A specific entry learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()

    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Inner class used by Django to determine the usage of the class"""
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model"""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text
    

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80, 'rows': 20})}

learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden


# Create your views here.
def index(request):
    """The home page for Learning Log"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Show all topics"""
    topics = Topic.objects.filter(user=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Show topic and related entries"""
    topic = Topic.objects.get(id=topic_id)
    return _check_user_access(topic, request)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Add a new topic"""
    if request.method != 'POST':
        # No data submitted create a blank form
        form = TopicForm()
    else:
        # Data submitted; process
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.user = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry related to the topic"""
    topic = Topic.objects.get(id=topic_id)

    return _check_user_access(topic, request)

    if request.method != 'POST':
        # No data submitted - create a blank form
        form = EntryForm()
    else:
        # Data submitted; process
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Display a blank or invalid form
    context = {'form': form, 'topic': topic}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edits an already existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    return _check_user_access(topic, request)

    if request.method != 'POST':
        # No data submitted - create a blank form, fill with previous value
        form = EntryForm()
    else:
        # Data submitted; process
        form = EntryForm(data=request.POST, instance=entry)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


def _check_user_access(topic, request):
    """Returns appropriate response object if user is not authorised"""
    if topic.user != request.user:
        return HttpResponseForbidden(request)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title%}</title>
</head>
<body>
  <p>
      <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
      <a href="{% url 'learning_logs:topics' %}">Topics</a> -
      {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout' %}">Log out</a>
      {% else %}
        <a href="{% url 'users:login' %}">Log in</a>
      {% endif %}
  </p>
{% block content %}{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html "%}

{% block title %}
Edit Entry {{entry.id}}
{% endblock title %}

{% block content %}

<p>Edit Entry {{entry.id}}</p>
<form action="{% url 'learning_logs:edit_entry' entry.id%}" method="post">
    <p>previously: {{entry}}</p>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Finish editing</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block title %}
Index website
{% endblock title %}

{% block content %}
<p>Learning Log</p>
<p>Learning Log helps you keep track of your learning</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block title %}
Add Entry to {{topic}}
{% endblock title %}

{% block content %}
<a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
<p>Add new entry:</p>

<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Add entry</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>Add a new topic</p>
<form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add topic</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block title %}
Topic - {{topic}}
{% endblock title %}

{% block content %}
<p>Topic: {{topic}}</p>
<p>Entries:</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>Date: {{entry.date_added}}</p>
        <p>Entry: {{entry.text}}</p>
        <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit this entry</a>
    </li>
    {% empty %}
    <li>No entries associated with this entry yet</li>
    {% endfor %}

</ul>
<a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry related to this topic</a>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block title %}
Topics page
{% endblock title %}

{% block content %}

<p>Topics</p>
<ul>
  <a href="{% url 'learning_logs:new_topic' %}">Add new topic</a>
  {% for topic in topics %}
    <li><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></li>
    {% empty %}
    <li>No topics added yet</li>
    {% endfor %}
</ul>

{% endblock content %}